<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="download">
	<div class="btn-group">
		<a class="btn" title="<?php _e('Add Category'); ?>" href="<?php echo $this->url('', array('controller' => 'category', 'action' => 'update')); ?>"><i class="icon-list-alt"></i> <?php _e('Add Category'); ?></a>
		<a class="btn" title="<?php _e('Add File'); ?>" href="<?php echo $this->url('', array('controller' => 'file', 'action' => 'update')); ?>"><i class="icon-folder-open"></i> <?php _e('Add File'); ?></a>
	</div>
	<h3><?php _e('List of categories'); ?></h3>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('ID'); ?></th>
			<th><?php _e('Title'); ?></th>
			<th><?php _e('Create'); ?></th>
			<th><?php _e('Action'); ?></th>
		</tr>
		<?php foreach($categories as $category) { ?>
		<tr>
			<td><?php echo $this->escape($category['id']); ?></td>
			<td><?php echo $this->escape($category['title']); ?></td>
			<td><?php echo $this->escape($category['create']); ?></td>
			<td>
				<div class="btn-group">
					<a class="btn" title="<?php _e('View'); ?>" href="<?php echo $this->url('.download', array('module' => $module, 'controller' => 'category', 'alias' => $this->escape($category['alias']))); ?>"><i class="icon-eye-open"></i> <?php _e('View'); ?></a>
					<a class="btn" title="<?php _e('Files'); ?>" href="<?php echo $this->url('', array('controller' => 'file', 'action' => 'index', 'category' => $category['id'])); ?>"><i class="icon-edit"></i> <?php _e('Files'); ?></a>
					<a class="btn" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', array('controller' => 'category', 'action' => 'update', 'id' => $category['id'])); ?>"><i class="icon-edit"></i> <?php _e('Edit'); ?></a>
					<a class="btn" title="<?php _e('Delete'); ?>" href="<?php echo $this->url('', array('controller' => 'category', 'action' => 'delete', 'id' => $category['id'])); ?>"><i class="icon-trash"></i> <?php _e('Delete'); ?></a>
				</div>
			</td>
		</tr>
		<?php } ?>
	</table>
	<div class="paginator"><?php echo $this->paginationControl($categories, 'Sliding', 'paginator'); ?></div>
</div>