<?php
    $this->css(array(
        $this->assetModule('css/admin.css'),
        $this->assetModule('script/system-ui.css', 'system'),
    ));
    $this->jQuery();
    $this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<div class="download">
	<div class="btn-group">
		<a class="btn" title="<?php _e('Back'); ?>" href="<?php echo $this->url('', array('action' => 'index')); ?>"><i class="icon-arrow-left"></i> <?php _e('Back'); ?></a>
		<a class="btn" title="<?php _e('Add Category'); ?>" href="<?php echo $this->url('', array('controller' => 'category', 'action' => 'update')); ?>"><i class="icon-list-alt"></i> <?php _e('Add Category'); ?></a>
		<a class="btn" title="<?php _e('Add File'); ?>" href="<?php echo $this->url('', array('controller' => 'file', 'action' => 'update')); ?>"><i class="icon-folder-open"></i> <?php _e('Add File'); ?></a>
	</div>
	<br />
	<h2><?php echo $this->escape($title); ?></h2>
	<div id="category-form">
	<?php include $this->templateComponent('form'); ?>
	</div>
</div> 
<script type="text/javascript" >
(function($){
    $("#category-form").on("click","button",function(){
       systemMessage.wait("<?php _e('Remove image file in process'); ?>");
       $.getJSON($(this).attr("data-link")).done(function(result){
          if(result.status==1){
             systemMessage.succ(result.message);
          }else{
             systemMessage.fail(result.message);
          }
       });
    });
})(jQuery)
</script>