<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="download">
	<div class="btn-group">
	   <?php if(isset($back)) { ?>
	   <a class="btn" title="<?php _e('Back'); ?>" href="<?php echo $this->url('', array('action' => 'index')); ?>"><i class="icon-arrow-left"></i> <?php _e('Back'); ?></a>
	   <?php } ?>
		<a class="btn" title="<?php _e('Add Category'); ?>" href="<?php echo $this->url('', array('controller' => 'category', 'action' => 'update')); ?>"><i class="icon-list-alt"></i> <?php _e('Add Category'); ?></a>
		<a class="btn" title="<?php _e('Add File'); ?>" href="<?php echo $this->url('', array('controller' => 'file', 'action' => 'update')); ?>"><i class="icon-folder-open"></i> <?php _e('Add File'); ?></a>
	</div>
	<h3><?php _e('List of files'); ?></h3>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('ID'); ?></th>
			<th><?php _e('Title'); ?></th>
			<th><?php _e('Category'); ?></th>
			<th><?php _e('Create'); ?></th>
			<th><?php _e('Action'); ?></th>
		</tr>
		<?php foreach($files as $file) { ?>
		<tr>
			<td><?php echo $this->escape($file['id']); ?></td>
			<td><?php echo $this->escape($file['title']); ?></td>
			<td><a title="<?php echo $this->escape($file['categorytitle']); ?>" href="<?php echo $this->url('', array('controller' => 'file', 'action' => 'index', 'category' => $file['categoryid'])); ?>"><?php echo $this->escape($file['categorytitle']); ?></a></td>
			<td><?php echo $this->escape($file['create']); ?></td>
			<td>
				<div class="btn-group">
				   <a class="btn" title="<?php _e('View'); ?>" href="#"><i class="icon-eye-open"></i> <?php _e('View'); ?></a>
					<a class="btn" title="<?php _e('Manage source'); ?>" href="<?php echo $this->url('', array('controller' => 'file', 'action' => 'attach', 'id' => $file['id'])); ?>"><i class="icon-edit"></i> <?php _e('Manage source'); ?></a>
					<a class="btn" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', array('controller' => 'file', 'action' => 'update', 'id' => $file['id'])); ?>"><i class="icon-edit"></i> <?php _e('Edit'); ?></a>
					<a class="btn" title="<?php _e('Delete'); ?>" href="<?php echo $this->url('', array('controller' => 'file', 'action' => 'delete', 'id' => $file['id'])); ?>"><i class="icon-trash"></i> <?php _e('Delete'); ?></a>
				</div>
			</td>
		</tr>
		<?php } ?>
	</table>
	<div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator'); ?></div>
</div>	