CREATE TABLE `{category}` (
  `id` int(10) unsigned NOT NULL  auto_increment,
  `pid` int(5) unsigned NOT NULL,
  `title` varchar(255) NOT NULL,
  `alias` varchar(255) NOT NULL,
  `information` text,
  `keywords` varchar(255) NOT NULL,
  `description` varchar(255) NOT NULL,
  `status` tinyint(1) unsigned NOT NULL,
  `create` int(10) unsigned NOT NULL,
  `image` varchar(255) NOT NULL,
  `path` varchar(16) NOT NULL,
  `count` int(10) unsigned NOT NULL,
  `order` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `alias` (`alias`),
  KEY `pid` (`pid`),
  KEY `status` (`status`),
  KEY `create` (`create`),
  KEY `order` (`order`),
  KEY `category_list` (`pid`, `status`, `order`)
); 

CREATE TABLE `{file}` (
  `id` int(10) unsigned NOT NULL  auto_increment,
  `category` int(10) unsigned NOT NULL,
  `title` varchar(255) NOT NULL,
  `alias` varchar(255) NOT NULL,
  `information` text,
  `keywords` varchar(255) NOT NULL,
  `description` varchar(255) NOT NULL,
  `status` tinyint(1) unsigned NOT NULL,
  `create` int(10) unsigned NOT NULL,
  `author` int(10) unsigned NOT NULL,
  `view` int(10) unsigned NOT NULL,
  `download` int(10) unsigned NOT NULL,
  `image` varchar(255) NOT NULL,
  `path` varchar(16) NOT NULL,
  `comments` int(10) unsigned NOT NULL,
  `point` int(10) NOT NULL,
  `count` int(10) unsigned NOT NULL,
  `source` tinyint(3) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `alias` (`alias`),
  KEY `status` (`status`),
  KEY `create` (`create`),
  KEY `author` (`author`),
  KEY `view` (`view`),
  KEY `download` (`download`),
  KEY `comments` (`comments`),
  KEY `point` (`point`),
  KEY `source` (`source`),
  KEY `file_list` (`category`, `source`, `create`)
); 

CREATE TABLE `{source}` (
  `id` int(10) unsigned NOT NULL  auto_increment,
  `file` int(10) unsigned NOT NULL,
  `type` enum('archive','image','video','audio','pdf','doc','other','link') NOT NULL,
  `location` enum('internal','external') NOT NULL,
  `title` varchar(255) NOT NULL,
  `mimetype`  varchar(255) NOT NULL,
  `status` tinyint(1) unsigned NOT NULL,
  `create` int(10) unsigned NOT NULL,
  `death` int(10) unsigned NOT NULL,
  `link` varchar(255) NOT NULL,
  `source` varchar(255) NOT NULL,
  `path` varchar(16) NOT NULL,
  `url` varchar(64) NOT NULL,
  `ip` varchar(15) NOT NULL,
  `size` int(10) unsigned NOT NULL,
  `author` int(10) unsigned NOT NULL,
  `download` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `file` (`file`),
  KEY `mimetype` (`mimetype`),
  KEY `location` (`location`),
  KEY `type` (`type`),
  KEY `status` (`status`),
  KEY `create` (`create`),
  KEY `death` (`death`),
  KEY `author` (`author`),
  KEY `download` (`download`),
  KEY `source_list` (`file`, `status`, `create`)
);

CREATE TABLE `{limit}` (
  `id` int(10) unsigned NOT NULL  auto_increment,
  `file` int(10) unsigned NOT NULL,
  `source` int(4) unsigned NOT NULL,
  `user` int(10) unsigned NOT NULL,
  `ip` varchar(15) NOT NULL,
  `create` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `file` (`file`),
  KEY `source` (`source`),
  KEY `user` (`user`),
  KEY `ip` (`ip`),
  KEY `create` (`create`),
  KEY `limit_list` (`file`, `source`, `user`, `ip`)
);

CREATE TABLE `{submitter}` (
  `id` int(10) unsigned NOT NULL  auto_increment,
  `author` int(10) NOT NULL,
  `count` int(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `author` (`author`),
  KEY `count` (`count`)
);